version: '3.1'
services:
  db-alerts:
    image: "postgres:latest"
    environment:
      POSTGRES_DB:       prelude
      POSTGRES_USER:     prelude
      POSTGRES_PASSWORD_FILE: /run/secrets/alerts_db
    networks:
      - alerts
    secrets:
      - alerts_db
    volumes:
      - db-alerts:/var/lib/pgsql/data

  db-gui:
    image: "postgres:latest"
    environment:
      POSTGRES_DB:       prewikka
      POSTGRES_USER:     prewikka
      POSTGRES_PASSWORD_FILE: /run/secrets/gui_db
    networks:
      - gui
    secrets:
      - gui_db
    volumes:
      - db-gui:/var/lib/pgsql/data

  manager:
    depends_on:
      - db-alerts
    environment:
      ALERTS_DB_PASSWORD_FILE: /run/secrets/alerts_db
      SENSORS_PASSWORD_FILE:   /run/secrets/sensors
    secrets:
      - sensors
      - alerts_db
    ports:
      - "5553:5553"
      - "4690:4690"
    networks:
      - agents
      - alerts

  correlator:
    depends_on:
      - manager
      - db-alerts
    environment:
      ALERTS_DB_PASSWORD_FILE: /run/secrets/alerts_db
      SENSORS_PASSWORD_FILE: /run/secrets/sensors
    secrets:
      - alerts_db
      - sensors
    networks:
      - agents
      - alerts

  lml:
    depends_on:
      - manager
    environment:
      SENSORS_PASSWORD_FILE: /run/secrets/sensors
    secrets:
      - sensors
    ports:
      - "514:514/tcp"
      # Uncomment the next line to accept logs in the syslog format
      # on UDP port 514.
#      - "514:514/udp"
    networks:
      - agents

  prewikka:
    depends_on:
      - db-alerts
      - db-gui
      - manager
    environment:
      ALERTS_DB_PASSWORD_FILE: /run/secrets/alerts_db
      GUI_DB_PASSWORD_FILE:    /run/secrets/gui_db
    ports:
      - "80:80"
    secrets:
      - alerts_db
      - gui_db
    networks:
      - alerts
      - gui

  prewikka-crontab:
    depends_on:
      - db-alerts
      - db-gui
      - manager
    environment:
      ALERTS_DB_PASSWORD_FILE: /run/secrets/alerts_db
      GUI_DB_PASSWORD_FILE:    /run/secrets/gui_db
    secrets:
      - alerts_db
      - gui_db
    networks:
      - alerts
      - gui


volumes:
  db-alerts:
    driver: local
  db-gui:
    driver: local


networks:
  alerts:
  gui:
  agents:


secrets:
  alerts_db:
    file: secrets/alerts_db
  gui_db:
    file: secrets/gui_db
  sensors:
    file: secrets/sensors
