version: '3.1'
services:
  injector:
    image: "logstash:7.9.2"
    depends_on:
      - elasticsearch
      - lml
    environment:
      MONITORING_ENABLED:       "false"
      xpack.monitoring.enabled: "false"
      SYSLOG_TIMEZONE:          "${SYSLOG_TIMEZONE}"
    networks:
      - injector2logs
      - injector2lml
      - gui2injector
    volumes:
      - ./files/usr/share/logstash/pipeline/:/usr/share/logstash/pipeline/:ro
      - ./files/usr/share/logstash/template.json:/usr/share/logstash/template.json:ro
    ports:
      - "514:6514/tcp"
      # Uncomment the next line to accept logs in the syslog format
      # on UDP port 514.
      - "514:6514/udp"

  kibana:
    image: "kibana:7.9.2"
    ports:
      - "5601:5601"
    volumes:
      - elasticsearch:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - injector2logs
      - logs
    environment:
     SERVER_NAME : kibana
     ELASTICSEARCH_URL : http://elasticsearch:9200

  elasticsearch:
    image: "elasticsearch:7.9.2"
    environment:
      discovery.type:                       single-node
      bootstrap.memory_lock:                "true"
      xpack.monitoring.collection.enabled:  "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - injector2logs
      - logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  db-alerts:
    image: "postgres:latest"
    environment:
      POSTGRES_DB:              prelude
      POSTGRES_USER:            prelude
      POSTGRES_PASSWORD_FILE:   /run/secrets/alerts_db
    networks:
      - alerts
    secrets:
      - alerts_db
    volumes:
      - db-alerts:/var/lib/pgsql/data

  db-gui:
    image: "postgres:latest"
    environment:
      POSTGRES_DB:              prewikka
      POSTGRES_USER:            prewikka
      POSTGRES_PASSWORD_FILE:   /run/secrets/gui_db
    networks:
      - gui
    secrets:
      - gui_db
    volumes:
      - db-gui:/var/lib/pgsql/data

  manager:
    depends_on:
      - db-alerts
    environment:
      ALERTS_DB_PASSWORD_FILE:  /run/secrets/alerts_db
      SENSORS_PASSWORD_FILE:    /run/secrets/sensors
    secrets:
      - sensors
      - alerts_db
    ports:
      - "5553:5553"
      - "4690:4690"
    networks:
      - agents
      - alerts

  correlator:
    depends_on:
      - manager
      - db-alerts
    environment:
      ALERTS_DB_PASSWORD_FILE:  /run/secrets/alerts_db
      SENSORS_PASSWORD_FILE:    /run/secrets/sensors
    secrets:
      - alerts_db
      - sensors
    networks:
      - agents
      - alerts

  lml:
    depends_on:
      - manager
    environment:
      SENSORS_PASSWORD_FILE:    /run/secrets/sensors
    secrets:
      - sensors
    networks:
      - agents
      - injector2lml

  prewikka:
    depends_on:
      - db-alerts
      - db-gui
      - elasticsearch
      - injector
      - manager
    environment:
      ALERTS_DB_PASSWORD_FILE:  /run/secrets/alerts_db
      GUI_DB_PASSWORD_FILE:     /run/secrets/gui_db
      SYSLOG_TIMEZONE:          "${SYSLOG_TIMEZONE}"
    ports:
      - "80:80"
    secrets:
      - alerts_db
      - gui_db
    networks:
      - alerts
      - gui
      - gui2injector
      - logs

  prewikka-crontab:
    depends_on:
      - db-alerts
      - db-gui
      - elasticsearch
      - manager
    environment:
      ALERTS_DB_PASSWORD_FILE:  /run/secrets/alerts_db
      GUI_DB_PASSWORD_FILE:     /run/secrets/gui_db
    secrets:
      - alerts_db
      - gui_db
    networks:
      - alerts
      - gui
      - logs


volumes:
  db-alerts:
    driver: local
  db-gui:
    driver: local
  elasticsearch:
    driver: local


networks:
  agents:
  alerts:
  gui:
  gui2injector:
  injector2lml:
  injector2logs:
  logs:


secrets:
  alerts_db:
    file: secrets/alerts_db
  gui_db:
    file: secrets/gui_db
  sensors:
    file: secrets/sensors
